# Generated by Django 4.2.6 on 2023-10-22 22:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('documento_identidad', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='Invalid DNI', message='Utilice solo números, longitud 4-12', regex='^([0-9]{4,12})$')])),
                ('nombres', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='Invalid name', message='Utilice solo letras', regex='^([a-zA-ZñÑáéíóúÁÉÍÓÚ ]{1,30})$')])),
                ('apellidos', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='Invalid lastname', message='Utilice solo letras', regex='^([a-zA-ZñÑáéíóúÁÉÍÓÚ ]{1,30})$')])),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('celular', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid cell phone number', message='Utilice solo números (no se acepta espacios)', regex='^([0-9]{10})$')])),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='Invalid ISBN', message='Utilice solo números, la longitud debe ser de 13 dígitos', regex='^([0-9]{13})$')])),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=19, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_renta', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.estudiante')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('evento', models.CharField(blank=True, max_length=300)),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.renta')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sexo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.tipodocumento'),
        ),
    ]
